pluginManagement {
    settings.ext.canReachIran = false
    try {
        def timeout = 2000
        def address = InetAddress.getByName("maven.myket.ir")
        def reachable = address.isReachable(timeout)

        if (reachable) {
            ext.canReachIran = true
            println "Iranian mirror reachable"
        } else {
            println "Iranian mirror not reachable"
        }
    } catch (Exception e) {
        ext.canReachIran = false
        println "Iranian mirror unreachable: " + e.getMessage()
    }

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        if (settings.ext.canReachIran) {
            maven { url 'https://maven.myket.ir' }
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        if (settings.ext.canReachIran) {
            maven { url 'https://maven.myket.ir' }
        }
        maven { url 'https://jitpack.io' }
    }
}

rootProject.name = "Ghostide"

include(":app", ":logcat", ":terminal-emulator", ":terminal-view")
include(':editor')
include(':components')
include(':materialfileicon')
include(':aimodel')
include(':jgit')
include(':prddownloader')
include ':musicpreview'
include(':plugin-api')
include(':ide-api')
include(':ide-ui-api')
//include(':proot')